openapi: 3.0.0
info:
  title: Camera API
  version: 1.0.0
servers:
  - url: 'http://localhost:8000/api/v1'
    description: Use your camera
paths:
  /:
    get:
      summary: 'Information about application'
      description: 'Basic information: api version, build information, etc...'
      operationId: ''
      responses:
        default:
          description: Default error sample response
################################################################################
  /system:
    get:
      summary: 'System information'
      description: 'System runtime information: mem, cpu, net load, etc...'
      operationId: ''
      responses:
        default:
          description: Default error sample response
################################################################################
  /debug:
    get:
      summary: '???'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  /debug/mpp:
    get:
      summary: 'HiMPP debug'
      description: 'Mapping /proc/umap/* to http api'
      operationId: ''
      responses:
        default:
          description: Default error sample response
################################################################################          
  /channel:
    get:
      summary: 'List of availible channels'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  /channel/{id}:
    parameters:
      - name: id
        in: path
        schema:
            type: integer
        description: Channel id
        required: true
    get:
      summary: 'Get information about channel'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response        
    patch:
      summary: 'Change channel settings'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response               
  /channel/{id}/enable:
    parameters:
      - name: id
        in: path
        schema:
            type: integer
        description: Channel id
        required: true
    post:
      summary: 'Enable channel'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response        
    delete:
      summary: 'Disable channel'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response             
################################################################################          
  /encoder:
    get:
      summary: 'List of avalible encoders'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  /encoder/jpeg:
    get:
      summary: 'Get list of JPEG encoder instances'
      description: ''
      operationId: ''
      responses:
        '200':
          description: 'Success'
          content: 
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int8
                    channel_id:
                      type: integer
                      format: int8
                    width:
                      type: integer
                      format: int16
                    height:
                      type: integer
                      format: int16
                    q:
                      type: integer
                      format: int8
              examples:
                test:
                  summary: 'Example responce'
                  value:
                  - id: 0
                    channel_id: 0
                    width: 1920
                    height: 1080
                    q: 80
                  - id: 1
                    channel_id: 1
                    width: 1280
                    height: 720
                    q: 50
                  - id: 2
                    channel_id: 1
                    width: 640
                    height: 360
                    q: 20
        '500':
          description: 'Default error response'
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: integer
                  error_description:
                    type: string
    post:
      summary: 'Configure and add JPEG encoder instance'
      description: ''
      operationId: ''
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                channel_id:
                  type: integer
                  format: int8
                  description: 'Source channel id'
                width:
                  type: integer
                  format: int16
                  minimum: 2
                  maximum: 8192
                  multipleOf: 2
                  default: 640
                  description: 'Width of picture'
                height:
                  type: integer
                  format: int16
                  minimum: 2
                  maximum: 8192  
                  multipleOf: 2
                  default: 480
                  description: 'Height of picture'
                q:
                  type: integer
                  format: int8
                  minimum: 1
                  maximum: 99
                  default: 20
                  description: 'Quality???'
                #y_q:
                #  type: integer
                #  format: int32
                #  minimum: 1
                #  maximum: 255
                #  description: 'Y quantization'
                #cb_q:
                #  type: integer
                #  format: int32
                #  minimum: 1
                #  maximum: 255
                #  description: 'Cb quantization'
                #cr_q:
                #  type: integer
                #  format: int32
                #  minimum: 1
                #  maximum: 255
                #  description: 'Cr quantization'
            examples:
              test:
                summary: 'HD resolution middle quality'
                value:
                  channel_id: 2
                  width: 1280
                  height: 720
                  q: 50
      responses:
        default:
          description: Default error sample response                  
  /encoder/jpeg/{id}:
    parameters:
      - name: id
        in: path
        schema:
            type: integer
        description: 'JPEG encoder instance id'
        required: true
    get:
      summary: 'Get information about JPEG encoder instance'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response   
    patch:
      summary: 'Change JPEG encoder instance runtime settings'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response             
          
    delete:
      summary: 'Delete JPEG encoder instance'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response          
  /encoder/mjpeg:
    get:
      summary: 'Get list of MJPEG encoder instances'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
    post:
      summary: 'Configure and add MJPEG encoder instance'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response               
  /encoder/mjpeg/{id}:
    parameters:
      - name: id
        in: path
        schema:
            type: integer
        description: 'MJPEG encoder instance id'
        required: true
    get:
      summary: 'Get information about MJPEG encoder instance'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response        
    patch:
      summary: 'Change MJPEG encoder instance runtime settings'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response             
    delete:
      summary: 'Delete MJPEG encoder instance'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response             
  /encoder/h264:
    get:
      summary: 'Get list of H.264 encoder instances'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
    post:
      summary: 'Configure and add H.264 encoder instance'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response                 
  /encoder/h264/{id}:
    parameters:
      - name: id
        in: path
        schema:
            type: integer
        description: 'H.264 encoder instance id'
        required: true
    get:
      summary: 'Get information about H.264 encoder instance'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response          
    patch:
      summary: 'Change H.264 encoder instance runtime settings'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response             
    delete:
      summary: 'Delete H.264 encoder instance'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response           
  /encoder/h265:
    get:
      summary: 'Get list of H.265 encoder instances'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
    post:
      summary: 'Configure and add H.265 encoder instance'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response       
  /encoder/h265/{id}:
    parameters:
      - name: id
        in: path
        schema:
            type: integer
        description: 'H.265 encoder instance id'
        required: true
    get:
      summary: 'Get information about H.265 encoder instance'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response     
    patch:
      summary: 'Change H.265 encoder instance runtime settings'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response             
    delete:
      summary: 'Delete H.264 encoder instance'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response     
################################################################################
  /streamer:
    get:
      summary: 'List of avalible streamers'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  /streamer/jpeg-over-http:
    get:
      summary: 'TBD'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  /streamer/rtsp:
    get:
      summary: 'TBD'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  /streamer/video-to-storage:
    get:
      summary: 'TBD'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  
          
          
          
          
