openapi: 3.0.0
info:
  title: Camera API
  version: 1.0.0
servers:
  - url: 'http://localhost:8000/api/v1'
    description: Use your camera
paths:
  /:
    summary: MPP debug
    description: Mapping /proc/umap/* to http api
    get:
      summary: ''
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  /debug:
    summary: MPP debug
    description: Mapping /proc/umap/* to http api
    get:
      summary: ''
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  /debug/mpp:
    summary: MPP debug
    description: Mapping /proc/umap/* to http api
    get:
      summary: ''
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  /channel:
    summary: MPP debug
    description: Mapping /proc/umap/* to http api
    get:
      summary: ''
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  /channel/{id}:
    parameters:
      - name: id
        in: path
        schema:
            type: integer
        description: Channel id
        required: true
    summary: MPP debug
    description: Mapping /proc/umap/* to http api
    get:
      summary: ''
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  /encoder:
    summary: MPP debug
    description: Mapping /proc/umap/* to http api
    get:
      summary: ''
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  /encoder/jpeg:
    summary: MPP debug
    description: Mapping /proc/umap/* to http api
    get:
      summary: ''
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  /encoder/jpeg/{id}:
    parameters:
      - name: id
        in: path
        schema:
            type: integer
        description: Channel id
        required: true
    summary: MPP debug
    description: Mapping /proc/umap/* to http api
    get:
      summary: ''
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response         
  /encoder/mjpeg:
    summary: MPP debug
    description: Mapping /proc/umap/* to http api
    get:
      summary: ''
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  /encoder/mjpeg/{id}:
    parameters:
      - name: id
        in: path
        schema:
            type: integer
        description: Channel id
        required: true
    summary: MPP debug
    description: Mapping /proc/umap/* to http api
    get:
      summary: ''
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response               
  /encoder/h264:
    summary: MPP debug
    description: Mapping /proc/umap/* to http api
    get:
      summary: ''
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  /encoder/h264/{id}:
    parameters:
      - name: id
        in: path
        schema:
            type: integer
        description: Channel id
        required: true
    summary: MPP debug
    description: Mapping /proc/umap/* to http api
    get:
      summary: ''
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response               
  /encoder/h265:
    summary: MPP debug
    description: Mapping /proc/umap/* to http api
    get:
      summary: ''
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  /encoder/h265/{id}:
    parameters:
      - name: id
        in: path
        schema:
            type: integer
        description: Channel id
        required: true
    summary: MPP debug
    description: Mapping /proc/umap/* to http api
    get:
      summary: ''
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response               
  /streamer:
    summary: MPP debug
    description: Mapping /proc/umap/* to http api
    get:
      summary: ''
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  /streamer/jpeg-over-http:
    summary: MPP debug
    description: Mapping /proc/umap/* to http api
    get:
      summary: ''
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  /streamer/rtsp:
    summary: MPP debug
    description: Mapping /proc/umap/* to http api
    get:
      summary: ''
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
