openapi: 3.0.0
info:
  title: Camera API
  version: 1.0.0
servers:
  - url: 'http://localhost:8000/api/v1'
    description: Use your camera
paths:
  /:
    get:
      summary: 'Information about application'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  /debug:
    get:
      summary: '???'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  /debug/mpp:
    get:
      summary: 'HiMPP debug'
      description: 'Mapping /proc/umap/* to http api'
      operationId: ''
      responses:
        default:
          description: Default error sample response
################################################################################          
  /channel:
    get:
      summary: 'List of availible channels'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  /channel/{id}:
    parameters:
      - name: id
        in: path
        schema:
            type: integer
        description: Channel id
        required: true
    get:
      summary: 'Get information about channel'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response        
    patch:
      summary: 'Change channel settings'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response               
  /channel/{id}/enable:
    parameters:
      - name: id
        in: path
        schema:
            type: integer
        description: Channel id
        required: true
    post:
      summary: 'Enable channel'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response        
    delete:
      summary: 'Disable channel'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response             
################################################################################          
  /encoder:
    get:
      summary: 'List of avalible encoders'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  /encoder/jpeg:
    get:
      summary: 'Get list of JPEG encoder instances'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
    post:
      summary: 'Configure and add JPEG encoder instance'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response                  
  /encoder/jpeg/{id}:
    parameters:
      - name: id
        in: path
        schema:
            type: integer
        description: Channel id
        required: true
    get:
      summary: 'Get information about JPEG encoder instance'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response   
    patch:
      summary: 'Change JPEG encoder instance runtime settings'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response             
          
    delete:
      summary: 'Delete JPEG encoder instance'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response          
  /encoder/mjpeg:
    get:
      summary: 'Get list of MJPEG encoder instances'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
    post:
      summary: 'Configure and add MJPEG encoder instance'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response               
  /encoder/mjpeg/{id}:
    parameters:
      - name: id
        in: path
        schema:
            type: integer
        description: ''
        required: true
    get:
      summary: 'Get information about MJPEG encoder instance'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response        
    patch:
      summary: 'Change MJPEG encoder instance runtime settings'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response             
    delete:
      summary: 'Delete MJPEG encoder instance'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response             
  /encoder/h264:
    get:
      summary: 'Get list of H.264 encoder instances'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
    post:
      summary: 'Configure and add H.264 encoder instance'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response                 
  /encoder/h264/{id}:
    parameters:
      - name: id
        in: path
        schema:
            type: integer
        description: Channel id
        required: true
    get:
      summary: 'Get information about H.264 encoder instance'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response          
    patch:
      summary: 'Change H.264 encoder instance runtime settings'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response             
    delete:
      summary: 'Delete H.264 encoder instance'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response           
  /encoder/h265:
    get:
      summary: 'Get list of H.265 encoder instances'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
    post:
      summary: 'Configure and add H.265 encoder instance'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response       
  /encoder/h265/{id}:
    parameters:
      - name: id
        in: path
        schema:
            type: integer
        description: Channel id
        required: true
    get:
      summary: 'Get information about H.265 encoder instance'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response     
    patch:
      summary: 'Change H.265 encoder instance runtime settings'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response             
    delete:
      summary: 'Delete H.264 encoder instance'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response     
################################################################################
  /streamer:
    get:
      summary: 'List of avalible streamers'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  /streamer/jpeg-over-http:
    get:
      summary: 'TBD'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  /streamer/rtsp:
    get:
      summary: 'TBD'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  /streamer/video-to-storage:
    get:
      summary: 'TBD'
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  
          
          
          
          
