#!/bin/sh
#
# Start the network....
#

# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

MAC     = `fw_printenv -n ethaddr`
IP      = `fw_printenv -n ipaddr`
MASK    = `fw_printenv -n netmask`
GATEWAY = `fw_printenv -n gateway`

case "$1" in
  start)
	printf "Starting network: "
	echo ``
	ifconfig eth0 down
	ifconfig eth0 hw ether $MAC
	ifconfig eth0 up
	/sbin/ifup -a
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping network: "
	/sbin/ifdown -a
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

