#!/bin/sh
# Useage: ./loadxm530 [ -r|-i|-a ]
#         -r : rmmod all modules
#         -i : insmod all modules
#    default : rmmod all moules and then insmod them
#

#内存和地址单位M
MEM_ALL=64
MEM_START=0x800
MEM_SAMALL_LIN=0x1

MEM_OS=32 
#`cat /proc/cmdline  | awk '{print $1}' | sed -e 's/mem=//' -e 's/M//'`
MEM_LEN=`echo "$MEM_ALL $MEM_OS"|awk '{printf("0x%03x00000",$1-$2)}'`
MEM_START=`echo "$MEM_START $MEM_SAMALL_LIN $MEM_OS"|awk '{printf("0x%03x00000",$1+$2*$3)}'`
echo MEM_START=$MEM_START  MEM_LEN=$MEM_LEN

VI_BUFF=2

report_error()
{
	echo "******* Error: There's something wrong, please check! *****"
		exit 1
}

insert_audio()
{
	echo "insert audio"
	insmod xm_i2s.ko
	insmod acodec.ko
}

remove_audio()
{
	echo "remove audio"
	rmmod acodec
	rmmod xm510_i2s
}

insert_sns()
{
	insmod xm_i2c.ko;
}

remove_sns()
{
	rmmod xm_i2c &> /dev/null
	rmmod ssp_sony &> /dev/null
}

insert_ko()
{
# driver load
		insert_sns > /dev/null
		insmod mmz.ko mmz_start=$MEM_START mmz_size=$MEM_LEN
		insmod xm530_vi.ko buffer=$VI_BUFF
		insmod xm530_isp.ko
		insmod xm530_rgn.ko
		insmod xm530_h264.ko
		insmod xm_rtc.ko
		#insmod xm_wdt.ko
		insmod log.ko

		#insert_audio
}

remove_ko()
{
	#remove_audio
	#rmmod xm_wdt
	rmmod xm_rtc
	rmmod xm530_h264
	rmmod xm530_rgn
	rmmod xm530_isp
	rmmod xm530_vi
	rmmod mmz

	remove_sns
}

load_usage()
{
	echo "Usage:  ./loadxm530 [-option]"
		echo "options:"
		echo "    -i                       insert modules"
		echo "    -r                       remove modules"
		echo "    -h                       help information"
		echo -e "for example: ./loadxm530 -i\n"
}

# load module.
if [ "$1" = "-i" ]
then
insert_ko
fi

if [ "$1" = "-r" ]
then
remove_ko
fi

if [ "$1" = "-h" ]
then
load_usage
exit
fi

if [ $# -eq 0 ] || [ "$1" = "-a" ]
then
remove_ko
insert_ko
fi

