/*
 * Camera API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse500 struct {

	ErrorCode int32 `json:"error_code,omitempty"`

	ErrorDescription string `json:"error_description,omitempty"`
}
