/*
 * Camera API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse200 struct {

	Id int32 `json:"id,omitempty"`

	ChannelId int32 `json:"channel_id,omitempty"`

	Width int32 `json:"width,omitempty"`

	Height int32 `json:"height,omitempty"`

	Q int32 `json:"q,omitempty"`
}
