openapi: 3.0.0
info:
  title: test
  version: 1.0.0
  contact:
    name: 'ererer'
    url: 'dfsdfsdf'

################################################################################

paths:

  /system:
    get:
      tags:
        - system
      summary: 'Get application general build information'
      operationId: 'system'
      responses:
        '200':
          description: 'Success'
          content:
            text/plain:
              schema:
               type: string

  /system/temperature:
    get:
      tags:
        - system
      summary: 'Get internal sensor temperature'
      operationId: 'systemTemperature'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemTemperature'
        '501':
          description: 'Not implemented'

  /system/date:
    get:
      tags:
        - system
      summary: 'Get system date and time'
      operationId: 'systemDate'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemDateTime'

  /system/network:
    get:
      tags:
        - system
      summary: 'Get network information'
      operationId: 'systemNetwork'
      responses:
        '200':
          description: 'Success'
          content:
            text/plain:
              schema:
               type: string

################################################################################

tags:
  - name: system
    description: General system information and control
################################################################################

components:
  schemas:
    SystemTemperature:
      type: object
      properties:
        temperature_c:
          type: number
          format: float
        temperature_f:
          type: number
          format: float
        temperature_k:
          type: number
          format: float

    SystemDateTime:
      type: object
      properties:
        formatted:
          type: string
          format: date-time
        secs:
          type: integer
          format: uint64
        nanosecs:
          type: integer
          format: uint64


