openapi: 3.0.0
info:
  title: test
  version: 1.0.0
  contact: 
    name: 'ererer'
    url: 'dfsdfsdf'

################################################################################

paths: 
    $ref: './system.yaml#/paths' 

################################################################################

tags:
  - name: system
    description: General system information and control
################################################################################

components:
  schemas:
    SystemTemperature:
      type: object
      properties:
        temperature_c:
          type: number
          format: float
        temperature_f:
          type: number
          format: float
        temperature_k:
          type: number
          format: float

    SystemDateTime:
      type: object
      properties:
        formatted:
          type: string
          format: date-time
        secs:
          type: integer
          format: uint64
        nanosecs:
          type: integer
          format: uint64


