# This Makefile is used to build uImage from Kernel's source tree

# the file is supposed to contain build parameters
MAKEFILE_PARAMS ?= "../Makefile.params"
-include $(MAKEFILE_PARAMS)

ifndef TOOLCHAIN
    $(error TOOLCHAIN variable MUST be defined)
endif

build:
	make -C ./linux clean
	make -C ./linux -j8 ARCH=arm CROSS_COMPILE=$(TOOLCHAIN) uImage
	cp -f ./linux/arch/arm/boot/uImage ./uImage
