openapi: 3.0.1
info:
    #$ref: "info.yaml#/info"
    title: GoHisiCam
    version: VERSION
    x-logo:
        url: "GOPHER200"
        backgroundColor: "#FFFFFF"
        altText: "GoHisiCam"
        href: "#"
    contact:
        email: info@openhisiipcam.org
        url: https://www.openhisiipcam.org
    description: 
        $ref: "info.yaml#/info/description"
      

paths:
  /:
      get:
        tags:
              - other
        summary: "Get API information"
        operationId: 'api123'
        responses:
            '200':
                description: 'Success'
                content: 
                    application/json:
                        schema:
                            type: object
            #            properties:
            #                formatted:
            #                type: string
 

  /openapi.json:
    $ref: "~misc.yml#/openapi.json"
  /openapi.yml:
      $ref: "~misc.yml#/openapi.yml"


  /api/system/date:
      $ref: "~system.yml#/date"

  /api/debug/umap:
    $ref: "~debug.yml#/umap"
  /api/debug/umap/{file}:
    $ref: "~debug.yml#/umap~1{file}"

  /api/mpp/cmos:
      $ref: "~cmos.yml#/cmos"

  /api/mpp/channel:
      $ref: "~channel.yml#/channel"
  /api/mpp/channel/{id}:
      $ref: "~channel.yml#/channel~1{id}"

  /api/mpp/venc:
    $ref: "~venc.yml#/venc"
  /api/mpp/venc/{id}:
    $ref: "~venc.yml#/venc~1{id}"

  /api/streamer/jpeg:
    $ref: "~jpeg.yml#/jpeg"
  /api/streamer/jpeg/{id}:
    $ref: "~jpeg.yml#/jpeg~1{id}"
  /jpeg/{name}.jpg:
    $ref: "~jpeg.yml#/~1{name}.jpg"

    #  /jpeg/1920_1080.jpg:
    #    get:
    #      tags:
    #        - jpeg
    #      summary: 'Get jpeg image 1920x1080 resolution'
    #      operationId: 'serveJpeg1920x1080'
    #      responses:
    #        '200':
    #          description: 'Success'
    #          content:
    #            image/jpeg:
    #              schema:
    #               type: string
    #               format: binary
    #  /jpeg/3840_2160.jpg:
    #    get:
    #      tags:
    #        - jpeg
    #      summary: 'Get jpeg image 3840x2160 resolution'
    #      operationId: 'serveJpeg3840x2160'
    #      responses:
    #        '200':
    #          description: 'Success'
    #          content:
    #            image/jpeg:
    #              schema:
    #               type: string
    #               format: binary
               
  /api/streamer/rtp:
    $ref: "~rtp.yml#/rtp"
  /api/streamer/rtp/{id}:
    $ref: "~rtp.yml#/rtp~1{id}"

#  /file:
#      $ref: "_file.yml#/record"

               #components:
               #venc:
               #schemas:
               #$ref: "venc.yml#/components/schemas"
        #    - $ref: "venc.yml#/components/schemas"
        #    - $ref: "system.yml#/components/schemas"
            
x-tagGroups:
  - name: General API
    description: "dfs dflkdsjflk jslfdj"
    tags:
        - system
        - debug
  - name: Audio/video pipeline API
    tags:
        - cmos
        - channel
        - venc
  - name: Streamers API
    tags:
      - jpeg
      - file
      - pipe
      - rtp
  - name: Unsorted API
    tags:
        - other
        - misc

tags:
  - name: system
    description: 
        $ref: "system.yml#/description"
    x-displayName: System

  - name: debug
    description: 
        $ref: "debug.yml#/description"
    x-displayName: Debug 
    #x-traitTag: true

  - name: cmos
    description:
        $ref: "cmos.yml#/description"
    x-displayName: CMOS

  - name: channel
    description: 
        $ref: "channel.yml#/description"
    x-displayName: Channels

  - name: venc
    description: 
        $ref: "venc.yml#/description"
    x-displayName: Encoders

  - name: jpeg
    description: "jpeg.yml#/description"
    x-displayName: Jpeg

  - name: file
    description: 
        $ref: "file.yml#/description"
    x-displayName: Files

  - name: pipe
    description:
        $ref: "pipe.yml#/description"
    x-displayName: Pipe

  - name: rtp
    description:
        $ref: "rtp.yml#/description"
    x-displayName: RTP


  - name: other
    description: |
        Other API methods
    x-displayName: Other

  - name: misc
    description: 
        $ref: "misc.yml#/description"
    x-displayName: Misc

