build: testvideo.h264
	go build -a

run: build
	./webrtc_tests

testvideo.h264:
	ffmpeg -f lavfi -i testsrc=size=320x340 -t 30 -pix_fmt yuv420p -c:v libx264 -tune zerolatency -profile:v high -g 25 -vbsf h264_mp4toannexb -f h264 testvideo.h264

clean:
	rm -f ./webrtc_tests
	rm -f ./testvideo.h264
