//+build arm
//+build hi3516cv500
//+build debug

package errmpp


var (
    codes = map[uint] codeInfo {
        0xA0028003: codeInfo{name: "HI_ERR_SYS_ILLEGAL_PARAM", desc: "The parameter configuration is invalid."},
        0xA0028006: codeInfo{name: "HI_ERR_SYS_NULL_PTR", desc: "The pointer is null."},
        0xA0028008: codeInfo{name: "HI_ERR_SYS_NOT_SUPPORT", desc: "The function is not supported."},
        0xA0028009: codeInfo{name: "HI_ERR_SYS_NOT_PERM", desc: "The operation is forbidden."},
        0xA0028010: codeInfo{name: "HI_ERR_SYS_NOTREADY", desc: "The system control attributes are not configured."},
        0xA0028012: codeInfo{name: "HI_ERR_SYS_BUSY", desc: "The system is busy."},
        0xA002800C: codeInfo{name: "HI_ERR_SYS_NOMEM", desc: "The memory fails to be allocated due to some causes such as insufficient system memory."},
        0xA0018003: codeInfo{name: "HI_ERR_VB_ILLEGAL_PARAM", desc: "The parameter configuration is invalid."},
        0xA0018005: codeInfo{name: "HI_ERR_VB_UNEXIST", desc: "The VB pool does not exist."},
        0xA0018006: codeInfo{name: "HI_ERR_VB_NULL_PTR", desc: "The pointer is null."},
        0xA0018009: codeInfo{name: "HI_ERR_VB_NOT_PERM", desc: "The operation is forbidden."},
        0xA001800C: codeInfo{name: "HI_ERR_VB_NOMEM", desc: "The memory fails to be allocated."},
        0xA001800D: codeInfo{name: "HI_ERR_VB_NOBUF", desc: "The buffer fails to be allocated."},
        0xA0018010: codeInfo{name: "HI_ERR_VB_NOTREADY", desc: "The system control attributes are not configured."},
        0xA0018012: codeInfo{name: "HI_ERR_VB_BUSY", desc: "The system is busy."},
        0xA0018013: codeInfo{name: "HI_ERR_VB_SIZE_NOT_ENOUGH", desc: "The VB size is too small."},
        0xA0018040: codeInfo{name: "HI_ERR_VB_2MPOOLS", desc: "Too many VB pools are created."},
        0xA0108001: codeInfo{name: "HI_ERR_VI_INVALID_DEVID", desc: "The VI device ID is invalid."},
        0xA0108002: codeInfo{name: "HI_ERR_VI_INVALID_CHNID", desc: "The VI channel ID is invalid."},
        0xA0108003: codeInfo{name: "HI_ERR_VI_INVALID_PARA", desc: "The VI parameter is invalid."},
        0xA0108004: codeInfo{name: "HI_ERR_VI_PIPE_EXIST", desc: "A pipe already exists."},
        0xA0108005: codeInfo{name: "HI_ERR_VI_PIPE_UNEXIST", desc: "A pipe does not exist."},
        0xA0108006: codeInfo{name: "HI_ERR_VI_INVALID_NULL_PTR", desc: "The pointer of the input parameter is null."},
        0xA0108007: codeInfo{name: "HI_ERR_VI_FAILED_NOTCONFIG", desc: "The attributes of the video device are not set."},
        0xA0108008: codeInfo{name: "HI_ERR_VI_NOT_SUPPORT", desc: "The operation is not supported."},
        0xA0108009: codeInfo{name: "HI_ERR_VI_NOT_PERM", desc: "The operation is forbidden."},
        0xA010800A: codeInfo{name: "HI_ERR_VI_INVALID_PIPEID", desc: "The pipe ID is invalid."},
        0xA010800B: codeInfo{name: "HI_ERR_VI_INVALID_STITCHGRPID", desc: "The stitching group is invalid."},
        0xA010800C: codeInfo{name: "HI_ERR_VI_NOMEM", desc: "The memory fails to be allocated."},
        0xA010800E: codeInfo{name: "HI_ERR_VI_BUF_EMPTY", desc: "The VI buffer is empty."},
        0xA010800F: codeInfo{name: "HI_ERR_VI_BUF_FULL", desc: "The VI buffer is full."},
        0xA0108010: codeInfo{name: "HI_ERR_VI_SYS_NOTREADY", desc: "The VI system is not initialized."},
        0xA0108012: codeInfo{name: "HI_ERR_VI_BUSY", desc: "The VI system is busy."},
        0xA0108040: codeInfo{name: "HI_ERR_VI_FAILED_NOTENABLE", desc: "The VI device is not enabled."},
        0xA0108041: codeInfo{name: "HI_ERR_VI_FAILED_NOTDISABLE", desc: "The VI device is not disabled."},
        0xA0108042: codeInfo{name: "HI_ERR_VI_FAILED_CHNOTDISABLE", desc: "The VI channel is not disabled."},
        0xA0108043: codeInfo{name: "HI_ERR_VI_CFG_TIMEOUT", desc: "The video attribute configuration times out."},
        0xA0108044: codeInfo{name: "HI_ERR_VI_NORM_UNMATCH", desc: "Mismatch occurs."},
        0xA0108045: codeInfo{name: "HI_ERR_VI_INVALID_WAYID", desc: "The video path ID is invalid."},
        0xA0108047: codeInfo{name: "HI_ERR_VI_FAILED_NOTBIND", desc: "The video channel is not bound."},
        0xA0108048: codeInfo{name: "HI_ERR_VI_FAILED_BINDED", desc: "The video channel is bound."},
        0xA0108049: codeInfo{name: "HI_ERR_VI_DIS_PROCESS_FAIL", desc: "The DIS fails to run."},
        0xA00F8001: codeInfo{name: "HI_ERR_VO_INVALID_DEVID", desc: "The device ID does not fall within the value range."},
        0xA00F8002: codeInfo{name: "HI_ERR_VO_INVALID_CHNID", desc: "The channel ID does not fall within the value range."},
        0xA00F8003: codeInfo{name: "HI_ERR_VO_ILLEGAL_PARAM", desc: "The parameter value does not fall within the value range."},
        0xA00F8006: codeInfo{name: "HI_ERR_VO_NULL_PTR", desc: "The pointer is null."},
        0xA00F8008: codeInfo{name: "HI_ERR_VO_NOT_SUPPORT", desc: "The operation is not supported."},
        0xA00F8009: codeInfo{name: "HI_ERR_VO_NOT_PERMIT", desc: "The operation is forbidden."},
        0xA00F800C: codeInfo{name: "HI_ERR_VO_NO_MEM", desc: "The memory is insufficient."},
        0xA00F8010: codeInfo{name: "HI_ERR_VO_SYS_NOTREADY", desc: "The system is not initialized."},
        0xA00F8012: codeInfo{name: "HI_ERR_VO_BUSY", desc: "The resources are unavailable."},
        0xA00F8040: codeInfo{name: "HI_ERR_VO_DEV_NOT_CONFIG", desc: "The VO device is not configured."},
        0xA00F8041: codeInfo{name: "HI_ERR_VO_DEV_NOT_ENABLE", desc: "The VO device is not enabled."},
        0xA00F8042: codeInfo{name: "HI_ERR_VO_DEV_HAS_ENABLED", desc: "The VO device has been enabled."},
        0xA00F8043: codeInfo{name: "HI_ERR_VO_DEV_HAS_BINDED", desc: "The device has been bound."},
        0xA00F8044: codeInfo{name: "HI_ERR_VO_DEV_NOT_BINDED", desc: "The device is not bound."},
        0xA00F8045: codeInfo{name: "HI_ERR_VO_VIDEO_NOT_ENABLE", desc: "The video layer is not enabled."},
        0xA00F8046: codeInfo{name: "HI_ERR_VO_VIDEO_NOT_DISABLE", desc: "The video layer is not disabled."},
        0xA00F8047: codeInfo{name: "HI_ERR_VO_VIDEO_NOT_CONFIG", desc: "The video layer is not configured."},
        0xA00F8048: codeInfo{name: "HI_ERR_VO_CHN_NOT_DISABLE", desc: "The VO channel is not disabled."},
        0xA00F8049: codeInfo{name: "HI_ERR_VO_CHN_NOT_ENABLE", desc: "No VO channel is enabled."},
        0xA00F804A: codeInfo{name: "HI_ERR_VO_CHN_NOT_CONFIG", desc: "The VO channel is not configured."},
        0xA00F804B: codeInfo{name: "HI_ERR_VO_CHN_NOT_ALLOC", desc: "No VO channel is allocated."},
        0xA00F804C: codeInfo{name: "HI_ERR_VO_INVALID_PATTERN", desc: "The pattern is invalid."},
        0xA00F804D: codeInfo{name: "HI_ERR_VO_INVALID_POSITION", desc: "The cascade position is invalid."},
        0xA00F804E: codeInfo{name: "HI_ERR_VO_WAIT_TIMEOUT", desc: "Waiting times out."},
        0xA00F804F: codeInfo{name: "HI_ERR_VO_INVALID_VFRAME", desc: "The video frame is invalid."},
        0xA00F8050: codeInfo{name: "HI_ERR_VO_INVALID_RECT_PARA", desc: "The rectangle parameter is invalid."},
        0xA00F8051: codeInfo{name: "HI_ERR_VO_SETBEGIN_ALREADY", desc: "The SETBEGIN MPI has been configured."},
        0xA00F8052: codeInfo{name: "HI_ERR_VO_SETBEGIN_NOTYET", desc: "The SETBEGIN MPI is no configured."},
        0xA00F8053: codeInfo{name: "HI_ERR_VO_SETEND_ALREADY", desc: "The SETEND MPI has been configured."},
        0xA00F8054: codeInfo{name: "HI_ERR_VO_SETEND_NOTYET", desc: "The SETEND MPI is not configured."},
        0xA00F8055: codeInfo{name: "HI_ERR_VO_GRP_INVALID_ID", desc: "The group ID is invalid."},
        0xA00F8056: codeInfo{name: "HI_ERR_VO_GRP_NOT_CREATE", desc: "The group is not created."},
        0xA00F8057: codeInfo{name: "HI_ERR_VO_GRP_HAS_CREATED", desc: "The group has been created."},
        0xA00F8058: codeInfo{name: "HI_ERR_VO_GRP_NOT_DESTROY", desc: "The group has not been destroyed."},
        0xA00F8059: codeInfo{name: "HI_ERR_VO_GRP_CHN_FULL", desc: "The group channel is full."},
        0xA00F805A: codeInfo{name: "HI_ERR_VO_GRP_CHN_EMPTY", desc: "The group channel is empty."},
        0xA00F805B: codeInfo{name: "HI_ERR_VO_GRP_CHN_NOT_EMPTY", desc: "The group channel is not empty."},
        0xA00F805C: codeInfo{name: "HI_ERR_VO_GRP_INVALID_SYN_MODE", desc: "The group synchronization mode is invalid."},
        0xA00F805D: codeInfo{name: "HI_ERR_VO_GRP_INVALID_BASE_PTS", desc: "The basic PTS of the group is invalid."},
        0xA00F805E: codeInfo{name: "HI_ERR_VO_GRP_NOT_START", desc: "The group is not started."},
        0xA00F805F: codeInfo{name: "HI_ERR_VO_GRP_NOT_STOP", desc: "The group is not stopped."},
        0xA00F8060: codeInfo{name: "HI_ERR_VO_GRP_INVALID_FRMRATE", desc: "The group frame rate is invalid."},
        0xA00F8061: codeInfo{name: "HI_ERR_VO_GRP_CHN_HAS_REG", desc: "The group channel has been registered."},
        0xA00F8062: codeInfo{name: "HI_ERR_VO_GRP_CHN_NOT_REG", desc: "The group channel is not registered."},
        0xA00F8063: codeInfo{name: "HI_ERR_VO_GRP_CHN_NOT_UNREG", desc: "The group channel is not deregistered."},
        0xA00F8064: codeInfo{name: "HI_ERR_VO_GRP_BASE_NOT_CFG", desc: "The basic information of the group is not configured."},
        0xA00F8065: codeInfo{name: "HI_ERR_VO_GFX_NOT_DISABLE", desc: "The graphics layer is not disabled."},
        0xA00F8066: codeInfo{name: "HI_ERR_VO_GFX_NOT_BIND", desc: "The graphics layer is not bound."},
        0xA00F8067: codeInfo{name: "HI_ERR_VO_GFX_NOT_UNBIND", desc: "The graphics layer is bound."},
        0xA00F8068: codeInfo{name: "HI_ERR_VO_GFX_INVALID_ID", desc: "The graphics layer ID does not fall within the value range."},
        0xA00F8069: codeInfo{name: "HI_ERR_VO_WBC_NOT_DISABLE", desc: "The WD is not disabled."},
        0xA00F806A: codeInfo{name: "HI_ERR_VO_WBC_NOT_CONFIG", desc: "The WD is not configured."},
        0xA00F806B: codeInfo{name: "HI_ERR_VO_CHN_AREA_OVERLAP", desc: "The VO channel areas overlap."},
        0xA00F806C: codeInfo{name: "HI_ERR_VO_INVALID_WBCID", desc: "WBC number does not fall within the value range."},
        0xA00F806D: codeInfo{name: "HI_ERR_VO_INVALID_LAYERID", desc: " The video layer ID does not fall within the value range."},
        0xA00F806E: codeInfo{name: "HI_ERR_VO_VIDEO_HAS_BINDED", desc: "The video layer has been bound."},
        0xA00F806F: codeInfo{name: "HI_ERR_VO_VIDEO_NOT_BINDED", desc: "The video layer is not bound"},
        0xA00F8070: codeInfo{name: "HI_ERR_VO_WBC_HAS_BIND", desc: "The WD has been bound."},
        0xA00F8071: codeInfo{name: "HI_ERR_VO_WBC_HAS_CONFIG", desc: "The WD has been configured."},
        0xA00F8072: codeInfo{name: "HI_ERR_VO_WBC_NOT_BIND", desc: "The WD has not been bound."},
        0xA0078001: codeInfo{name: "HI_ERR_VPSS_INVALID_DEVID", desc: "The VPSS group ID is invalid."},
        0xA0078002: codeInfo{name: "HI_ERR_VPSS_INVALID_CHNID", desc: "The VPSS channel ID is invalid."},
        0xA0078003: codeInfo{name: "HI_ERR_VPSS_ILLEGAL_PARAM", desc: "The VPSS parameter is invalid."},
        0xA0078004: codeInfo{name: "HI_ERR_VPSS_EXIST", desc: "A VPSS group is created."},
        0xA0078005: codeInfo{name: "HI_ERR_VPSS_UNEXIST", desc: "No VPSS group is created."},
        0xA0078006: codeInfo{name: "HI_ERR_VPSS_NULL_PTR", desc: "The pointer of the input parameter is null."},
        0xA0078008: codeInfo{name: "HI_ERR_VPSS_NOT_SUPPORT", desc: "The operation is not supported."},
        0xA0078009: codeInfo{name: "HI_ERR_VPSS_NOT_PERM", desc: "The operation is forbidden."},
        0xA007800C: codeInfo{name: "HI_ERR_VPSS_NOMEM", desc: "The memory fails to be allocated."},
        0xA007800D: codeInfo{name: "HI_ERR_VPSS_NOBUF", desc: "The buffer pool fails to be allocated."},
        0xA007800E: codeInfo{name: "HI_ERR_VPSS_BUF_EMPTY", desc: "The image queue is empty."},
        0xA0078010: codeInfo{name: "HI_ERR_VPSS_NOTREADY", desc: "The VPSS is not initialized."},
        0xA0078012: codeInfo{name: "HI_ERR_VPSS_BUSY", desc: "The VPSS is busy."},
        0xA0078013: codeInfo{name: "HI_ERR_VPSS_SIZE_NOT_ENOUGH", desc: "The VB blocks are not big enough."},
        0xA0088002: codeInfo{name: "HI_ERR_VENC_INVALID_CHNID", desc: "The channel ID is invalid."},
        0xA0088003: codeInfo{name: "HI_ERR_VENC_ILLEGAL_PARAM", desc: "The parameter is invalid."},
        0xA0088004: codeInfo{name: "HI_ERR_VENC_EXIST", desc: "The device, channel or resource to be created or applied for exists."},
        0xA0088005: codeInfo{name: "HI_ERR_VENC_UNEXIST", desc: "The device, channel or resource to be used or destroyed does not exist."},
        0xA0088006: codeInfo{name: "HI_ERR_VENC_NULL_PTR", desc: "The parameter pointer is null."},
        0xA0088007: codeInfo{name: "HI_ERR_VENC_NOT_CONFIG", desc: "No parameter is set before use."},
        0xA0088008: codeInfo{name: "HI_ERR_VENC_NOT_SUPPORT", desc: "The parameter or function is not supported."},
        0xA0088009: codeInfo{name: "HI_ERR_VENC_NOT_PERM", desc: "The operation, for example, modifying static parameters, is forbidden."},
        0xA008800C: codeInfo{name: "HI_ERR_VENC_NOMEM", desc: "The memory fails to be allocated due to some causes such as insufficient system memory."},
        0xA008800D: codeInfo{name: "HI_ERR_VENC_NOBUF", desc: "The buffer fails to be allocated due to some causes such as oversize of the data buffer applied for."},
        0xA008800E: codeInfo{name: "HI_ERR_VENC_BUF_EMPTY", desc: "The buffer is empty."},
        0xA008800F: codeInfo{name: "HI_ERR_VENC_BUF_FULL", desc: "The buffer is full."},
        0xA0088010: codeInfo{name: "HI_ERR_VENC_SYS_NOTREADY", desc: "The system is not initialized or the corresponding module is not loaded."},
        0xA0088012: codeInfo{name: "HI_ERR_VENC_BUSY", desc: "The VENC system is busy."},
        0xA0058002: codeInfo{name: "HI_ERR_VDEC_INVALID_CHNID", desc: "The channel ID is invalid."},
        0xA0058003: codeInfo{name: "HI_ERR_VDEC_ILLEGAL_PARAM", desc: "The parameter value is invalid."},
        0xA0058004: codeInfo{name: "HI_ERR_VDEC_EXIST", desc: "The channel to be created exists already."},
        0xA0058005: codeInfo{name: "HI_ERR_VDEC_UNEXIST", desc: "No channel is created or the channel is destroyed."},
        0xA0058006: codeInfo{name: "HI_ERR_VDEC_NULL_PTR", desc: "The pointer is null."},
        0xA0058007: codeInfo{name: "HI_ERR_VDEC_NOT_CONFIG", desc: "The system or VDA channel is not configured."},
        0xA0058008: codeInfo{name: "HI_ERR_VDEC_NOT_SURPPORT", desc: "The parameter or function is not supported."},
        0xA0058009: codeInfo{name: "HI_ERR_VDEC_NOT_PERM", desc: "The operation is forbidden."},
        0xA005800C: codeInfo{name: "HI_ERR_VDEC_NOMEM", desc: "The memory fails to be allocated due to the causes such as insufficient system memory."},
        0xA005800D: codeInfo{name: "HI_ERR_VDEC_NOBUF", desc: "The buffer fails to be allocated due to some causes. For example, the data buffer applied for is too large."},
        0xA005800E: codeInfo{name: "HI_ERR_VDEC_BUF_EMPTY", desc: "The buffer is empty."},
        0xA005800F: codeInfo{name: "HI_ERR_VDEC_BUF_FULL", desc: "The buffer is full."},
        0xA0058010: codeInfo{name: "HI_ERR_VDEC_SYS_NOTREADY", desc: "The system is not initialized or the dependent driver is not loaded."},
        0xA0058011: codeInfo{name: "HI_ERR_VDEC_BADADDR", desc: "The stream address is incorrect."},
        0xA0058012: codeInfo{name: "HI_ERR_VDEC_BUSY", desc: "The system is busy."},
        0xA0038001: codeInfo{name: "HI_ERR_RGN_INVALID_DEVID", desc: "The device ID exceeds the valid range."},
        0xA0038002: codeInfo{name: "HI_ERR_RGN_INVALID_CHNID", desc: "The channel ID is incorrect or the region handle is invalid."},
        0xA0038003: codeInfo{name: "HI_ERR_RGN_ILLEGAL_PARAM", desc: "The parameter value exceeds its valid range."},
        0xA0038004: codeInfo{name: "HI_ERR_RGN_EXIST", desc: "The device, channel, or resource to be created already exists."},
        0xA0038005: codeInfo{name: "HI_ERR_RGN_UNEXIST", desc: "The device, channel, or resource to be used or destroyed does not exist."},
        0xA0038006: codeInfo{name: "HI_ERR_RGN_NULL_PTR", desc: "The pointer is null."},
        0xA0038007: codeInfo{name: "HI_ERR_RGN_NOT_CONFIG", desc: "The module is not configured."},
        0xA0038008: codeInfo{name: "HI_ERR_RGN_NOT_SUPPORT", desc: "The parameter or function is not supported."},
        0xA0038009: codeInfo{name: "HI_ERR_RGN_NOT_PERM", desc: "The operation, for example, attempting to modify the value of a static parameter, is forbidden."},
        0xA003800C: codeInfo{name: "HI_ERR_RGN_NOMEM", desc: "The memory fails to be allocated due to some causes such as insufficient system memory."},
        0xA003800D: codeInfo{name: "HI_ERR_RGN_NOBUF", desc: "The buffer fails to be allocated due to some causes such as oversize of the data buffer applied for."},
        0xA003800E: codeInfo{name: "HI_ERR_RGN_BUF_EMPTY", desc: "The buffer is empty."},
        0xA003800F: codeInfo{name: "HI_ERR_RGN_BUF_FULL", desc: "The buffer is full."},
        0xA0038010: codeInfo{name: "HI_ERR_RGN_NOTREADY", desc: "The system is not initialized or the corresponding module is not loaded."},
        0xA0038011: codeInfo{name: "HI_ERR_RGN_BADADDR", desc: "The address is invalid."},
        0xA0038012: codeInfo{name: "HI_ERR_RGN_BUSY", desc: "The system is busy."},
        0xA0148003: codeInfo{name: "HI_ERR_AIO_ILLEGAL_PARAM", desc: "The settings of basic audio attributes are invalid."},
        0xA0148006: codeInfo{name: "HI_ERR_AIO_NULL_PTR", desc: "The pointer to the input parameter is null."},
        0xA0148009: codeInfo{name: "HI_ERR_AIO_NOT_PERM", desc: "This operation is not allowed."},
        0xA0148041: codeInfo{name: "HI_ERR_AIO_REGISTER_ERR", desc: "Registration failed."},
        0xA0158001: codeInfo{name: "HI_ERR_AI_INVALID_DEVID", desc: "The AI device ID is invalid."},
        0xA0158002: codeInfo{name: "HI_ERR_AI_INVALID_CHNID", desc: "The AI channel ID is invalid."},
        0xA0158003: codeInfo{name: "HI_ERR_AI_ILLEGAL_PARAM", desc: "The settings of the AI parameters are invalid."},
        0xA0158005: codeInfo{name: "HI_ERR_AI_NOT_ENABLED", desc: "The AI device or AI channel is not enabled."},
        0xA0158006: codeInfo{name: "HI_ERR_AI_NULL_PTR", desc: "The input parameter pointer is null."},
        0xA0158007: codeInfo{name: "HI_ERR_AI_NOT_CONFIG", desc: "The attributes of an AI device are not set."},
        0xA0158008: codeInfo{name: "HI_ERR_AI_NOT_SUPPORT", desc: "The operation is not supported."},
        0xA0158009: codeInfo{name: "HI_ERR_AI_NOT_PERM", desc: "The operation is forbidden."},
        0xA015800C: codeInfo{name: "HI_ERR_AI_NOMEM", desc: "The memory fails to be allocated."},
        0xA015800D: codeInfo{name: "HI_ERR_AI_NOBUF", desc: "The AI buffer is insufficient."},
        0xA015800E: codeInfo{name: "HI_ERR_AI_BUF_EMPTY", desc: "The AI buffer is empty."},
        0xA015800F: codeInfo{name: "HI_ERR_AI_BUF_FULL", desc: "The AI buffer is full."},
        0xA0158010: codeInfo{name: "HI_ERR_AI_SYS_NOTREADY", desc: "The AI system is not initialized."},
        0xA0158012: codeInfo{name: "HI_ERR_AI_BUSY", desc: "The AI system is busy."},
        0xA0158041: codeInfo{name: "HI_ERR_AI_VQE_ERR", desc: "A VQE processing error occurs in the AI channel."},
        0xA0168001: codeInfo{name: "HI_ERR_AO_INVALID_DEVID", desc: "The AO device ID is invalid."},
        0xA0168002: codeInfo{name: "HI_ERR_AO_INVALID_CHNID", desc: "The AO channel ID is invalid."},
        0xA0168003: codeInfo{name: "HI_ERR_AO_ILLEGAL_PARAM", desc: "The settings of the AO parameters are invalid."},
        0xA0168005: codeInfo{name: "HI_ERR_AO_NOT_ENABLED", desc: "The AO device or AO channel is not enabled."},
        0xA0168006: codeInfo{name: "HI_ERR_AO_NULL_PTR", desc: "The output parameter pointer is null."},
        0xA0168007: codeInfo{name: "HI_ERR_AO_NOT_CONFIG", desc: "The attributes of an AO device are not set."},
        0xA0168008: codeInfo{name: "HI_ERR_AO_NOT_SUPPORT", desc: "The operation is not supported."},
        0xA0168009: codeInfo{name: "HI_ERR_AO_NOT_PERM", desc: "The operation is forbidden."},
        0xA016800C: codeInfo{name: "HI_ERR_AO_NOMEM", desc: "The system memory is insufficient."},
        0xA016800D: codeInfo{name: "HI_ERR_AO_NOBUF", desc: "The AO buffer is insufficient."},
        0xA016800E: codeInfo{name: "HI_ERR_AO_BUF_EMPTY", desc: "The AO buffer is empty."},
        0xA016800F: codeInfo{name: "HI_ERR_AO_BUF_FULL", desc: "The AO buffer is full."},
        0xA0168010: codeInfo{name: "HI_ERR_AO_SYS_NOTREADY", desc: "The AO system is not initialized."},
        0xA0168012: codeInfo{name: "HI_ERR_AO_BUSY", desc: "The AO system is busy."},
        0xA0168041: codeInfo{name: "HI_ERR_AO_VQE_ERR", desc: "A VQE processing error occurs in the AO channel."},
        0xA0178001: codeInfo{name: "HI_ERR_AENC_INVALID_DEVID", desc: "The AENC device ID is invalid."},
        0xA0178002: codeInfo{name: "HI_ERR_AENC_INVALID_CHNID", desc: "The AENC channel ID is invalid."},
        0xA0178003: codeInfo{name: "HI_ERR_AENC_ILLEGAL_PARAM", desc: "The settings of the AENC parameters are invalid."},
        0xA0178004: codeInfo{name: "HI_ERR_AENC_EXIST", desc: "An AENC channel is created."},
        0xA0178005: codeInfo{name: "HI_ERR_AENC_UNEXIST", desc: "An AENC channel is not created."},
        0xA0178006: codeInfo{name: "HI_ERR_AENC_NULL_PTR", desc: "The input parameter pointer is null."},
        0xA0178007: codeInfo{name: "HI_ERR_AENC_NOT_CONFIG", desc: "The AENC channel is not configured."},
        0xA0178008: codeInfo{name: "HI_ERR_AENC_NOT_SUPPORT", desc: "The operation is not supported."},
        0xA0178009: codeInfo{name: "HI_ERR_AENC_NOT_PERM", desc: "The operation is forbidden."},
        0xA017800C: codeInfo{name: "HI_ERR_AENC_NOMEM", desc: "The system memory is insufficient."},
        0xA017800D: codeInfo{name: "HI_ERR_AENC_NOBUF", desc: "The buffer for AENC channels fails to be allocated."},
        0xA017800E: codeInfo{name: "HI_ERR_AENC_BUF_EMPTY", desc: "The AENC channel buffer is empty."},
        0xA017800F: codeInfo{name: "HI_ERR_AENC_BUF_FULL", desc: "The AENC channel buffer is full."},
        0xA0178010: codeInfo{name: "HI_ERR_AENC_SYS_NOTREADY", desc: "The system is not initialized."},
        0xA0178040: codeInfo{name: "HI_ERR_AENC_ENCODER_ERR", desc: "An AENC data error occurs."},
        0xA0178041: codeInfo{name: "HI_ERR_AENC_VQE_ERR", desc: "A VQE processing error occurs in the AENC channel."},
        0xA0188001: codeInfo{name: "HI_ERR_ADEC_INVALID_DEVID", desc: "The ADEC device is invalid."},
        0xA0188002: codeInfo{name: "HI_ERR_ADEC_INVALID_CHNID", desc: "The ADEC channel ID is invalid."},
        0xA0188003: codeInfo{name: "HI_ERR_ADEC_ILLEGAL_PARAM", desc: "The settings of the ADEC parameters are invalid."},
        0xA0188004: codeInfo{name: "HI_ERR_ADEC_EXIST", desc: "An ADEC channel is created."},
        0xA0188005: codeInfo{name: "HI_ERR_ADEC_UNEXIST", desc: "An ADEC channel is not created."},
        0xA0188006: codeInfo{name: "HI_ERR_ADEC_NULL_PTR", desc: "The input parameter pointer is null."},
        0xA0188007: codeInfo{name: "HI_ERR_ADEC_NOT_CONFIG", desc: "The attributes of an ADEC channel are not set."},
        0xA0188008: codeInfo{name: "HI_ERR_ADEC_NOT_SUPPORT", desc: "The operation is not supported."},
        0xA0188009: codeInfo{name: "HI_ERR_ADEC_NOT_PERM", desc: "The operation is forbidden."},
        0xA018800C: codeInfo{name: "HI_ERR_ADEC_NOMEM", desc: "The system memory is insufficient."},
        0xA018800D: codeInfo{name: "HI_ERR_ADEC_NOBUF", desc: "The buffer for ADEC channels fails to be allocated."},
        0xA018800E: codeInfo{name: "HI_ERR_ADEC_BUF_EMPTY", desc: "The ADEC channel buffer is empty."},
        0xA018800F: codeInfo{name: "HI_ERR_ADEC_BUF_FULL", desc: "The ADEC channel buffer is full."},
        0xA0188010: codeInfo{name: "HI_ERR_ADEC_SYS_NOTREADY", desc: "The system is not initialized."},
        0xA0188040: codeInfo{name: "HI_ERR_ADEC_DECODER_ERR", desc: "An ADEC data error occurs."},
        0xA0188041: codeInfo{name: "HI_ERR_ADEC_BUF_LACK", desc: "An insufficient buffer occurs in the ADEC channel."},
        0xA02D800E: codeInfo{name: "HI_ERR_VGS_BUF_EMPTY", desc: "The VGS jobs, tasks, or nodes are used up."},
        0xA02D8003: codeInfo{name: "HI_ERR_VGS_ILLEGAL_PARAM", desc: "The VGS parameter value is invalid."},
        0xA02D8006: codeInfo{name: "HI_ERR_VGS_NULL_PTR", desc: "The input parameter pointer is null."},
        0xA02D8008: codeInfo{name: "HI_ERR_VGS_NOT_SUPPORT", desc: "The operation is not supported."},
        0xA02D8009: codeInfo{name: "HI_ERR_VGS_NOT_PERMITTED", desc: "The operation is forbidden."},
        0xA02D800D: codeInfo{name: "HI_ERR_VGS_NOBUF", desc: "The memory fails to be allocated."},
        0xA02D8010: codeInfo{name: "HI_ERR_VGS_SYS_NOTREADY", desc: "The system is not initialized."},
        0xA02D800F: codeInfo{name: "HI_ERR_VGS_BUF_FULL", desc: "There is no buffer left."},
        0xA025800D: codeInfo{name: "HI_ERR_GDC_NOBUF", desc: "The memory fails to be allocated."},
        0xA025800E: codeInfo{name: "HI_ERR_GDC_BUF_EMPTY", desc: "The jobs, tasks, or nodes of the GDC are used up."},
        0xA0258006: codeInfo{name: "HI_ERR_GDC_NULL_PTR", desc: "The pointer of the input parameter is null."},
        0xA0258003: codeInfo{name: "HI_ERR_GDC_ILLEGAL_PARAM", desc: "The parameter configuration of GDC is invalid."},
        0xA0258010: codeInfo{name: "HI_ERR_GDC_SYS_NOTREADY", desc: "The system is not initialized."},
        0xA0258008: codeInfo{name: "HI_ERR_GDC_NOT_SUPPORT", desc: "This operation is not supported."},
        0xA0258009: codeInfo{name: "HI_ERR_GDC_NOT_PERMITTED", desc: "This operation is not allowed."},
        0xA0258012: codeInfo{name: "HI_ERR_GDC_BUSY", desc: "The GDC channel ID failed to be applied for."},
        0xA0258002: codeInfo{name: "HI_ERR_GDC_INVALID_CHNID", desc: "The GDC channel ID is invalid."},
        0xA0258005: codeInfo{name: "HI_ERR_GDC_CHN_UNEXIST", desc: "The GDC channel ID does not exist."},
        0xA0258011: codeInfo{name: "HI_ERR_FISHEYE_CALIBRATE_NULL_PTR", desc: "The pointer of the fisheye calibration input parameter is null."},
        0xA0258012: codeInfo{name: "HI_ERR_FISHEYE_CALIBRATE_ILLEGAL_PARAM", desc: "The parameter configuration of fisheye calibration is invalid."},
        0xA0258013: codeInfo{name: "HI_ERR_FISHEYE_CALIBRATE_NOT_SUPPORT", desc: "This operation is not supported."},
        0xA0068001: codeInfo{name: "HI_ERR_AVS_INVALID_DEVID", desc: "The AVS group ID is invalid."},
        0xA0068002: codeInfo{name: "HI_ERR_AVS_INVALID_CHNID", desc: "The AVS channel ID is invalid."},
        0xA0068003: codeInfo{name: "HI_ERR_AVS_ILLEGAL_PARAM", desc: "The AVS parameter setting is invalid."},
        0xA0068004: codeInfo{name: "HI_ERR_AVS_EXIST", desc: "An AVS group is created already."},
        0xA0068005: codeInfo{name: "HI_ERR_AVS_UNEXIST", desc: "An AVS group is not created yet."},
        0xA0068006: codeInfo{name: "HI_ERR_AVS_NULL_PTR", desc: "The pointer of the input parameter is null."},
        0xA0068008: codeInfo{name: "HI_ERR_AVS_NOT_SUPPORT", desc: "The operation is not supported."},
        0xA0068009: codeInfo{name: "HI_ERR_AVS_NOT_PERM", desc: "The operation is forbidden."},
        0xA006800A: codeInfo{name: "HI_ERR_AVS_INVALID_PIPEID", desc: "The AVS pipe ID is invalid."},
        0xA006800C: codeInfo{name: "HI_ERR_AVS_NOMEM", desc: "The memory fails to be allocated."},
        0xA006800D: codeInfo{name: "HI_ERR_AVS_NOBUF", desc: "The buffer fails to be allocated."},
        0xA006800E: codeInfo{name: "HI_ERR_AVS_BUF_EMPTY", desc: "The image queue is empty."},
        0xA0068010: codeInfo{name: "HI_ERR_AVS_NOTREADY", desc: "The AVS system is not initialized."},
        0xA0068012: codeInfo{name: "HI_ERR_AVS_BUSY", desc: "The AVS system is busy."},
        0xA01C8006: codeInfo{name: "HI_ERR_ISP_NULL_PTR", desc: "The input pointer is null."},
        0xA01C8003: codeInfo{name: "HI_ERR_ISP_ILLEGAL_PARAM", desc: "The input parameter is invalid."},
        0xA01C8008: codeInfo{name: "HI_ERR_ISP_NOT_SUPPORT", desc: "This function is not supported by the ISP."},
        0xA01C8043: codeInfo{name: "HI_ERR_ISP_SNS_UNREGISTER", desc: "The sensor is not registered."},
        0xA01C8041: codeInfo{name: "HI_ERR_ISP_MEM_NOT_INIT", desc: "The external registers are not initialized."},
        0xA01C8040: codeInfo{name: "HI_ERR_ISP_NOT_INIT", desc: "The ISP is not initialized."},
        0xA01C8044: codeInfo{name: "HI_ERR_ISP_INVALID_ADDR", desc: "The address is invalid."},
        0xA01C8042: codeInfo{name: "HI_ERR_ISP_ATTR_NOT_CFG", desc: "The attribute is not configured."},
        0xA01C8045: codeInfo{name: "HI_ERR_ISP_NOMEM", desc: "The memory is insufficient."},
        0xA01C8046: codeInfo{name: "HI_ERR_ISP_NO_INT", desc: "The ISP module has no interrupt."},
    }
)
