/*
 * Camera API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject struct {

	// Source channel id
	ChannelId int32 `json:"channel_id,omitempty"`

	// Width of picture
	Width int32 `json:"width,omitempty"`

	// Height of picture
	Height int32 `json:"height,omitempty"`

	// Quality???
	Q int32 `json:"q,omitempty"`
}
